export const CONTENT_ID = 'Content-ID';
export const CONTENT_ID_PREFIX = 'b29c5de2-0db4-490b-b421-6a51b598bd22';
export const CONTENT_TYPE = 'Content-Type';
export const CONTENT_TYPE_HTTP = 'application/http; msgtype=request';
export const CONTENT_TYPE_MIXED = 'multipart/mixed; boundary=';
export const CONTENT_TYPE_BATCH = 'multipart/batch; boundary=';
export const BOUNDARY = '1494052623884';
export const DOUBLE_DASH = '--';
export const NEW_LINE = '\r\n';
export const EMPTY_STRING = '';
export const SPACE = ' ';
export const HTTP_VERSION_1_1 = 'HTTP/1.1';
export const XSSI_PREFIX = /^\)\]\}",?\n/;
